tap "felixkratz/formulae"
tap "fielding/tap"
tap "hashicorp/tap"
tap "jackielii/tap"
tap "koekeishiya/formulae"
tap "oculus-vr/tap"
tap "runpod/runpodctl"
tap "supabase/tap"
brew "bat"
brew "cliproxyapi", restart_service: :changed
brew "cmake"
brew "coreutils"
brew "direnv"
brew "duckdb"
brew "expat"
brew "eza"
brew "fastfetch"
brew "ffmpeg"
brew "fnm"
brew "fzf"
brew "gh"
brew "git-delta"
brew "git-filter-repo"
brew "git-lfs"
brew "glow"
brew "imagemagick"
brew "libpq", link: true
brew "neovim"
brew "nmap"
brew "node"
brew "openjdk@17"
brew "pnpm"
brew "poppler"
brew "r"
brew "ripgrep"
brew "smartmontools"
brew "stow"
brew "syncthing", restart_service: :changed
brew "tailscale", restart_service: :changed
brew "tmux"
brew "unar"
brew "uv"
brew "xcodegen"
brew "yt-dlp"
brew "zbar"
brew "zig"
brew "zplug"
brew "zsh-syntax-highlighting"
brew "felixkratz/formulae/borders"
brew "felixkratz/formulae/sketchybar"
brew "hashicorp/tap/terraform"
cask "jackielii/tap/skhd-zig"
brew "koekeishiya/formulae/yabai"
brew "oculus-vr/tap/meta-xr-simulator"
brew "runpod/runpodctl/runpodctl"
# brew "supabase/tap/supabase"  # disabled 2026-06: upstream tap has a stale
# checksum (recorded SHA != download), which aborts the whole `brew bundle`
# transaction. Re-enable once the tap is fixed, or install supabase manually.
cask "1password-cli"
cask "android-studio"
cask "ayugram"
cask "caffeine"
cask "codex"
cask "db-browser-for-sqlite"
cask "discord"
cask "font-hack-nerd-font"
cask "font-inconsolata-go-nerd-font"
cask "font-inconsolata-lgc-nerd-font"
cask "font-sketchybar-app-font"
cask "ghostty"
cask "gimp"
cask "godot"
cask "orbstack"
cask "slack"
cask "unity-hub"
cargo "cargo-expand"
cargo "cargo-mutants"
cargo "cargo-nextest"
cargo "cargo-watch"
# git-factor is git-sourced (not on crates.io), so `brew bundle`'s cargo
# directive can't install it. bootstrap.sh installs it post-bundle via:
#   cargo install --git https://github.com/dkubb/git-factor
# (provides git-factor + git-sequence-editor)
cargo "sccache"
npm "@ollama/pi-web-search"
npm "corepack"
